### ISSUE TITLE
Windows 64bit Support

### ISSUE THREAD

**Issue by Srcsm** [AdamRaichu/vscode-minecraft-lang#9]
Any future plans on supporting 64-bit potentially?

Currently when trying to install in VSCode from the marketplace, it gives this message: `The 'Minecraft .lang Colorizer' extension is not available in Visual Studio Code for Windows 64 bit.`

**Comment by AdamRaichu** [comment]
I this is caused by me using the `--target web` flag in `vsce package`. I will test packaging without the `--target` flag.

**Comment by AdamRaichu** [comment]
Package uploaded, should be live shortly. Please reopen if I missed something in converting [extension.js](https://github.com/AdamRaichu/vscode-minecraft-lang/blob/main/extension.js) to [main.js](https://github.com/AdamRaichu/vscode-minecraft-lang/blob/main/main.js).
